name: flutter_starter_template
description: Adjusted template for a new flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3

  intl: ^0.16.1
  injectable: ^1.0.4
  auto_route: ^0.6.7
  supercharged: ^1.10.0
  dart_extensions: ^1.0.1

  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+2
  logger: ^0.9.2
  retrofit: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # previous versions had a bug with analysis (https://github.com/flutter/flutter/issues/56779)
  build_runner: ^1.10.1
  injectable_generator: any
  auto_route_generator: ^0.6.8
  mobx_codegen: ^1.1.0+1
  json_serializable: ^3.4.1
  retrofit_generator: any

flutter:
  uses-material-design: true  # includes the Material Icons font

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
